# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Batch

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FlatData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlatData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFlatData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FlatData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FlatData
    def Info(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Batch.DataArray import DataArray
            obj = DataArray()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FlatData
    def InfoLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FlatData
    def InfoIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # FlatData
    def Mask(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Batch.MaskArray import MaskArray
            obj = MaskArray()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FlatData
    def MaskLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FlatData
    def MaskIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def Start(builder): builder.StartObject(2)
def FlatDataStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddInfo(builder, info): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(info), 0)
def FlatDataAddInfo(builder, info):
    """This method is deprecated. Please switch to AddInfo."""
    return AddInfo(builder, info)
def StartInfoVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def FlatDataStartInfoVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartInfoVector(builder, numElems)
def AddMask(builder, mask): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(mask), 0)
def FlatDataAddMask(builder, mask):
    """This method is deprecated. Please switch to AddMask."""
    return AddMask(builder, mask)
def StartMaskVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def FlatDataStartMaskVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartMaskVector(builder, numElems)
def End(builder): return builder.EndObject()
def FlatDataEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)