runner:
  # --- Defaults ---
  max_iteration_num: 300
  pretrain: False
  render: False
  off_pg: False
  logger: False # False or True(OpenAI Logger)
  # --- Learning Condition ---
  batch_size: 30 # batch size
  self_play: False
  # --- Operation options ---
  use_cuda: True # Use gpu by default unless it isn't available
  history_path: "./history"
  figure_path: "./figures"
  best_model_root: "Best"
  condition_path: "./config/AlgoCondition.xlsx"
  draw_interval: 20