runner:
  # --- Defaults ---
  max_episode_num: 20000
  pretrain: True
  render: True
  # --- Learning Condition ---
  batch_size: 400 # batch size
  # --- Operation options ---
  use_cuda: True # Use gpu by default unless it isn't available
  history_path: "./history"
  best_model_root: "Best"
  condition_path: "./config/AlgoCondition.xlsx"
  off_pg: False
  logger: False # False or True(OpenAI Logger)
  iteration: 0
  multi_agent: False
  self_play: False
  # --- curriculum learning ---
  curriculum_learning: False
  init_n_of_enemy: 1
  next_phase_condition: "Clear" # Clear / Reward-val(point) / Kill-val(count) or Time-val(seconds)