runner:
  # --- Operation options ---
  use_cuda: True # Use gpu by default unless it isn't available
  history_path: "./history"
  best_model_root: "./history/BestAgent"
  condition_path: "./config/AlgoCondition.xlsx"
  off_pg: False
  agents: ['PPO']
  logger: False # False or True(OpenAI Logger)
  multi_agent: False
  self_play: False
  max_step_num: 800
  update_step: 50
  save_per_update: 4
  pretrain: True
  # --- curriculum learning ---
  curriculum_learning: False
  init_n_of_enemy: 1
  next_phase_condition: "Clear" # Clear / Reward-val(point) / Kill-val(count) or Time-val(seconds)