# --- Modules ---
runner_name: "StepRunner" # path about StepRunner / GymRunner / EpisodeRunner / AutoRLRunner
network_name: "CombatStrategy" # custom_network_path / torchvision.models(pre-trained)
env_name: "CombatStrategy" # Environment name (include gym.env)
agent_name: "PPO" # Algorithm name