# --- Modules ---
runner_name: "StepRunner" # path about episode / gym / ray_tune
network_name: "RLFPSv4" # custom_network_path / torchvision.models(pre-trained)
env_name: "RLFPSv4" # Environment name (include gym.env)
agent_name: "PPO" # Algorithm name