# --- Modules ---
runner_name: "GymRunner" # path about StepRunner / GymRunner / EpisodeRunner / AutoRLRunner
network_name: "LunarLander-v2" # custom_network_path / torchvision.models(pre-trained)
env_name: "LunarLander-v2" # Environment name (include gym.env)
agent_name: "SAC" # Algorithm nam