# --- Modules ---
runner_name: "gym" # path about StepRunner / gym / EpisodeRunner
network_name: "PathFindSim-v1" # custom_network_path / torchvision.models(pre-trained)
env_name: ["PathFindSim-v1"] # Environment name (include gym.env)
agent_name: "PPO" # Algorithm name