# --- Modules ---
runner_name: "GymRunner" # path about StepRunner / gym / EpisodeRunner
network_name: "CartPole-v1" # custom_network_path / torchvision.models(pre-trained)
env_name: "CartPole-v1" # Environment name (include gym.env)
agent_name: "PPO" # Algorithm name