# --- Modules ---
runner_name: "gym" # path about episode / gym / ray_tune
network_name: "RLFPSv4" # custom_network_path / torchvision.models(pre-trained)
env_name: "Hopper" # Environment name (include gym.env)