# --- Modules ---
runner_name: "EpisodeRunner" # path about StepRunner / GymRunner / EpisodeRunner / AutoRLRunner
network_name: "Graph" # custom_network_path / torchvision.models(pre-trained)
env_name: "Graph" # Environment name (include gym.env)
agent_name: "PPO" # Algorithm nam