# --- Modules ---
runner_name: "GymRunner" # path about StepRunner / GymRunner / EpisodeRunner
network_name: "Breakout-v4" # custom_network_path / torchvision.models(pre-trained)
env_name: ["Breakout-v4"] # Environment name (include gym.env)
agent_name: "PPO" # Algorithm name