# --- Modules ---
runner_name: "AutoRLRunner" # path about StepRunner / GymRunner / EpisodeRunner / AutoRLRunner
network_name: "Tennis-v4" # custom_network_path / torchvision.models(pre-trained)
env_name: "Tennis-v4" # Environment name (include gym.env)
agent_name: "PPO" # Algorithm name