network:
  actor:
    # --- learning option ---
    obs_stack: True # should not use Memory layer with this
    memory_q_len: "local" # Integer / List / String(Local)
    memory_layer_len: 4
    # - State definition -
    # --- spatial features ---
    spatial_feature:
      use: False
      memory_q_len: 4
      num_layer: 0
      dim_in: 0
      dim_out: 0
      backbone: 'resnet50'
      freeze: False
    # --- non-spatial features ---
    non_spatial_feature:
      use: True
      memory_q_len: 4
      num_layer: 0
      dim_in: 4
      dim_out: 64
      extension: True
      freeze: False
    # --- outputs ---
    neck_out: 16
    neck_activation: "ReLU"
    num_memory_layer: 0
    n_of_actions:
      - 2
    action_mode: "Discrete" # Discrete or Continuous
    # --- save / load ---
    model_path: 'Networks'