network:
  actor:
    # --- learning option ---
    obs_stack: True # should not use Memory layer with this
    memory_q_len: 57 # Integer / List / String(Local)
    # - State definition -
    # --- spatial features ---
    spatial_feature:
      use: False
      num_layer: 0
      dim_in: 0
      dim_out: 0
      backbone: 'resnet50'
      freeze: False
    # --- non-spatial features ---
    non_spatial_feature:
      use: True
      num_layer: 1
      dim_in: 4
      dim_out: 64
      extension: True
      use_cnn: False
      freeze: False
    # --- outputs ---
    neck_out: 8
    neck_activation: "ReLU"
    neck_num_layer: 1
    num_memory_layer: 6
    memory_rnn_len: 1
    n_of_actions:
      - 2
    action_mode: "Discrete" # Discrete or Continuous
    # --- save / load ---
    model_path: 'Networks'