network:
  # --- learning option ---
  obs_stack: True # should not use Memory layer with this
  use_memory_layer: ["Raw"] # Raw / LSTM / GRU
  memory_q_len: [1, 3]
  memory_layer_len: 3
  # - State definition -
  # --- spatial features ---
  spatial_feature:
    use: False
    dim_in: 0
    dim_out: 0
    backbone: 'resnet50'
    freeze: False
  # --- non-spatial features ---
  non_spatial_feature:
    use: True
    dim_in: 4
    dim_out: 4
    extension: False
    freeze: False
  # --- outputs ---
  neck_in: 12
  neck_out: 64
  neck_activation: "ReLU"
  n_of_actions:
    - 2
  # --- save / load ---
  model_path: 'Networks'
