network:
  # --- learning option ---
  obs_stack: True # should not use Memory layer with this
  use_memory_layer: ["Raw"] # Raw / LSTM / GRU
  memory_q_len: [1]
  memory_layer_len: 3
  # - State definition -
  # --- spatial features ---
  spatial_feature:
    use: True
    dim_in: 8
    dim_out: 128
    backbone: 'resnet50'
    freeze: False
  # --- non-spatial features ---
  non_spatial_feature:
    use: True
    dim_in: 180
    dim_out: 128
    extension: True
    freeze: False
  # --- outputs ---
  neck_in: 256
  neck_out: 32
  neck_activation: "ReLU"
  n_of_actions:
    - 9
    - 7
    - 3
  # --- save / load ---
  model_path: 'Networks'