network:
  # --- learning option ---
  obs_stack: True # should not use LSTM layer with this
  n_of_obs_stack: 3
  use_lstm: False
  n_of_lstm_layer: 3
  # - State definition -
  # --- spatial features ---
  spatial_feature:
    use: True
    dim: 7
    backbone: 'resnet50'
    freeze: False
  # --- non-spatial features ---
  non_spatial_feature:
    use: True
    dim: 26
    freeze: False
  # --- outputs ---
  neck_input: 128
  n_of_actions:
    - 2
  # --- save / load ---
  model_path: 'Networks'
