network:
  actor:
    # --- learning option ---
    obs_stack: False # should not use Memory layer with this
    use_memory_layer: "Raw" # Raw / LSTM / GRU
    memory_q_len: 1
    memory_layer_len: 1
    # - State definition -
    # --- spatial features ---
    spatial_feature:
      use: True
      dim_in: 8
      dim_out: 256
      backbone: ''
      freeze: False
    # --- non-spatial features ---
    non_spatial_feature:
      use: True
      dim_in: 180
      dim_out: 256
      extension: True
      freeze: False
    # --- outputs ---
    neck_activation: "ReLU"
    n_of_actions:
      - 9
      - 7
      - 3
    action_mode: "Discrete" # Discrete or Continuous
    # --- save / load ---
    model_path: 'Networks'