network:
  actor:
    # --- learning option ---
    obs_stack: True
    memory_q_len: 5 # Integer / List
    # - State definition -
    # --- spatial features ---
    spatial_feature:
      use: True
      num_layer: 3
      dim_in: [8, 30, 30]
      dim_out: 256
      backbone: ''
      freeze: False
    # --- non-spatial features ---
    non_spatial_feature:
      use: True
      num_layer: 3
      dim_in: 34 # oneonone: 34 3vs3: 102
      dim_out: 256
      extension: True
      use_cnn: True
      freeze: False
    # --- outputs ---
    neck_out: 32
    neck_activation: "ReLU"
    neck_num_layer: 3
    num_memory_layer: 0
    memory_rnn_len: 0
    n_of_actions:
      - 9
      - 7
      - 3
    action_mode: "Discrete" # Discrete or Continuous
    # --- save / load ---
    model_path: 'Networks'