envs:
  # --- Info ---
  name: CombatStrategy
  debug: False
  # --- Defaults ---
  port: 49999
  agent_count: 1
  enemy_count: 1
  agent_type: [-1]
  reward_range: [-5, 5]
  first_weapon_type: [1]
  second_weapon_type: [1]
  # --- learning condition ---
  mode: "Pause" # Pause or RealTime
  period: 200
  acceleration: 1.0
  update_steps: 50
  save_steps: 300
  max_steps: -1 # -1: No limit
  history_path: "./History"
  trajectory_q_len: 3
  # --- Algorithm condition ---
  actions: "Discrete" # Discrete or Continuous
  multi_agent: False
  self_play: False
  # --- curriculum learning ---
  curriculum_learning: False
  init_n_of_enemy: 1
  next_phase_condition: "Clear" # Clear / Reward-val(point) / Kill-val(count) or Time-val(seconds)
  # --- Feature parameters ---
  global_resolution: 100
  local_resolution: 30
  init_height: -5
  step_info_dim: 16
  spatial_dim: 15
  non_spatial_dim: 15
  maneuver_dim: 9
  stick_dim: 3


