envs:
  # --- Defaults ---
  name: OHTRouting
  reward_range: [-1, 1]
  trust_result: False
  # --- Simulator arguments(only string) ---
  args:
    view: "true"
    address: "127.0.0.1"
    dbname: "smat_2023_tiny"
    dbport: "3306"
    zmqport: "5555"
  # --- mix-up salt ---
  iteration: 5