agent:
  # --- Defaults ---
  name: "A2C"
  framework: "torch" # torch or tf
  gamma: 0.99 # discount factor
  actor_lr: 0.0001 # Actor learning rate
  critic_lr: 0.001 # Critic learning rate
  std_bound: [0.01, 1.0] # std. bound
  # - Model configuration -
  actor_optimizer: 'Adam'
  critic_optimizer: 'Adam'
  loss_function: 'MSELoss'
  # - Kinds of Action
  action: 'Discrete/Continuous'
