agent:
  gamma: 0.95 # discount factor
  actor_lr: 0.0001 # Actor learning rate
  critic_lr: 0.001 # Critic learning rate
  std_bound: [0.01, 1.0] # std. bound
  state_dim: 0 # You have to set this value (e.g. env.observation_space.shape[0])