agent:
  # --- Defaults ---
  name: "APEX-DQN"
  framework: "torch" # torch or tf
  # --- Hyper parameters ---
  gamma: 0.99
  epsilon: 0.4
  epsilon_alpha: 7.0
  epsilon_init: 1.0
  epsilon_min: 0.1
  epsilon_eval: 0.0
  explore_ratio: 0.1
  clip_grad_norm: 40.0
  target_update_period: 5
  # --- PER ---
  alpha: 0.5
  beta: 0.4
  learn_period: 2
  uniform_sample_prob: 0.001
  # - Model configuration
  actor_lr: 0.0001 # Actor learning rate
  optimizer: 'RMSprop'
  loss_function: 'SmoothL1Loss'
  buffer: 'PER'
  # - Kinds of Action
  action: 'Discrete'
