agent:
  # --- Defaults ---
  name: "APEX-DQN"
  framework: "torch" # torch or tf
  # --- Hyper parameters ---
  gamma: 0.99
  epsilon: 0.4
  epsilon_alpha: 7.0
  epsilon_init: 1.0
  epsilon_min: 0.1
  epsilon_eval: 0.0
  explore_ratio: 0.1
  clip_grad_norm: 40.0
  n_step: 4
  # - Model configuration -
  optimizer: 'Adam'
  loss_function: 'SmoothL1Loss'
  buffer: 'PER'
  # - Kinds of Action
  action: 'Discrete'
