agent:
  # --- Defaults ---
  name: "DDPG"
  framework: "torch" # torch or tf
  # --- Hyper parameters ---
  gamma: 0.99 # discount factor
  tau: 1e-2 # Tau
  actor_lr: 5e-4 # learning rate
  critic_lr: 5e-3
  clip_grad_param: 1 # Clip gradient parameter
  mu: 0
  theta: 1e-3
  sigma: 2e-3
  # --- Only Tensorflow ---
  #state_dim: 0 # You have to set this value (e.g. env.observation_space.shape[0])
  # - Model configuration -
  actor_optimizer: 'Adam'
  critic_optimizer: 'Adam'
  loss_function: 'MSELoss'
  buffer: 'Replay'
  # - Kinds of Action
  action: 'Continuous'
