agent:
  # --- Defaults ---
  name: "DQN"
  framework: "torch" # torch or tf
  # --- Hyper parameters ---
  gamma: 0.99 # discount factor
  epsilon: 0.4
  epsilon_alpha: 7.0
  epsilon_init: 1.0
  epsilon_min: 0.1
  epsilon_eval: 0.0
  explore_ratio: 0.1
  target_update_period: 5
  # - Model configuration -
  actor_lr: 0.0001 # Actor learning rate
  optimizer: 'Adam'
  loss_function: 'SmoothL1Loss'
  buffer: 'Replay'
  # - Kinds of Action
  action: 'Discrete'
