agent:
  # --- Defaults ---
  name: "Rainbow"
  framework: "torch" # torch or tf
  # --- Hyper parameters ---
  gamma: 0.99 # discount factor
  epsilon: 0.4
  epsilon_alpha: 7.0
  epsilon_init: 1.0
  epsilon_min: 0.1
  epsilon_eval: 0.0
  explore_ratio: 0.1
  n_step: 4
  noise_type: "factorized"
  v_min: -10
  v_max: 10
  num_support: 51
  # --- Only Tensorflow ---
  #state_dim: 0 # You have to set this value (e.g. env.observation_space.shape[0])
  # - Model configuration -
  optimizer: 'Adam'
  loss_function: 'MSELoss'
  # - Kinds of Action
  action: 'Discrete'