agent:
  # --- Defaults ---
  name: "Rainbow"
  framework: "torch" # torch or tf
  # --- Hyper parameters ---
  gamma: 0.99 # discount factor
  epsilon: 0.4
  epsilon_alpha: 7.0
  epsilon_init: 1.0
  epsilon_min: 0.1
  epsilon_eval: 0.0
  explore_ratio: 0.1
  v_min: -10
  v_max: 10
  num_support: 51
  target_update_period: 5
  # --- PER ---
  alpha: 0.5
  beta: 0.4
  learn_period: 2
  uniform_sample_prob: 0.001
  # --- Noisy ---
  noise_type: "factorized"  # [independent, factorized]
  # - Model configuration -
  actor_lr: 0.0001 # Actor learning rate
  optimizer: 'Adam'
  loss_function: 'MSELoss'
  # - Kinds of Action
  action: 'Discrete'