agent:
  # --- Defaults ---
  name: "discrete_sac_agent"
  framework: "torch" # torch or tf
  # --- Hyper parameters ---
  gamma: 0.99 # discount factor
  tau: 1e-2 # Tau
  lr: 5e-4 # learning rate
  clip_grad_param: 1 # Clip gradient parameter
  # --- Only Tensorflow ---
  #state_dim: 0 # You have to set this value (e.g. env.observation_space.shape[0])
  # - Model configuration -
  optimizer: 'Adam'
  loss_function: 'MSELoss'
