agent:
  # --- Defaults ---
  name: "SAC"
  framework: "torch" # torch or tf
  # --- Hyper parameters ---
  use_dynamic_alpha: False
  gamma: 0.99
  tau: 5e-3
  static_log_alpha: 2.0
  actor_lr: 5e-4,
  critic_lr: 1e-3,
  alpha_lr: 3e-4,
  # --- Only Tensorflow ---
  #state_dim: 0 # You have to set this value (e.g. env.observation_space.shape[0])
  # - Model configuration -
  actor_optimizer: 'Adam'
  critic_optimizer: 'Adam'
  alpha_optimizer: 'Adam'
  loss_function: 'MSELoss'
