vector-stacking:
  min: 1
  max: 64
vector-use_cnn: [True, False]
vector-layer_num:
  min: 1
  max: 4
vector-output_node: [16, 32, 64, 128, 256, 512, 1024]
matrix-stacking:
  min: 1
  max: 64
matrix-layer_num:
  min: 1
  max: 4
matrix-output_node: [16, 32, 64, 128, 256, 512, 1024]
neck-layer_num:
  min: 1
  max: 4
neck-use_rnn:
  min: 0
  max: 16
output-loss_function: ["CrossEntropyLoss", "MSELoss", "L1Loss", "NLLLoss"]
output-optimizer: ['SGD','Adam','AdaGrad','RMSprop']
output-batch_size:
  min: 20
  max: 300