network-spatial_feature-stacking:
  min: 1
  max: 64
network-spatial_feature-use_extension: [True, False]
network-spatial_feature-use_cnn: [True, False]
network-spatial_feature-layer_num:
  min: 1
  max: 4
network-spatial_feature-output_node: [16, 32, 64, 128, 256, 512, 1024]
network-non_spatial_feature-stacking:
  min: 1
  max: 64
network-non_spatial_feature-layer_num:
  min: 1
  max: 4
network-non_spatial_feature-output_node: [16, 32, 64, 128, 256, 512, 1024]
network-neck_layer_num:
  min: 1
  max: 4
network-neck_use_rnn_num:
  min: 0
  max: 8
network-neck_out: [8, 16, 32, 64, 128, 256]
agent-loss_function: ["CrossEntropyLoss", "MSELoss", "L1Loss"]
agent-optimizer: ['SGD','Adam','AdaGrad','RMSprop']
runner-batch_size:
  min: 20
  max: 300