// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace OHTMsg
{

public enum MsgType : sbyte
{
  None = 0,
  Reset = 1,
  Step = 2,
  Action = 3,
  DoneCheck = 4,
};


}
