# automatically generated by the FlatBuffers compiler, do not modify

# namespace: OHTMsg

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OHTReplyMsg(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OHTReplyMsg()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOHTReplyMsg(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OHTReplyMsg
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OHTReplyMsg
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # OHTReplyMsg
    def OhtId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OHTReplyMsg
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(3)
def OHTReplyMsgStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddType(builder, type): builder.PrependInt8Slot(0, type, 0)
def OHTReplyMsgAddType(builder, type):
    """This method is deprecated. Please switch to AddType."""
    return AddType(builder, type)
def AddOhtId(builder, ohtId): builder.PrependInt32Slot(1, ohtId, 0)
def OHTReplyMsgAddOhtId(builder, ohtId):
    """This method is deprecated. Please switch to AddOhtId."""
    return AddOhtId(builder, ohtId)
def AddAction(builder, action): builder.PrependInt32Slot(2, action, 0)
def OHTReplyMsgAddAction(builder, action):
    """This method is deprecated. Please switch to AddAction."""
    return AddAction(builder, action)
def End(builder): return builder.EndObject()
def OHTReplyMsgEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)